import type { Tournament } from './types.ts';

const tournaments: Tournament[] = [
  {
    title: 'Walt Disney Animation Studios films',
    description:
      '(Almost) every film released by Walt Disney Animation Studios. This does not include Pixar, Walt Disney Television Animation, etc.',
    players: [
      { name: 'Snow White and the Seven Dwarfs', score: 97, image: '' },
      { name: 'Pinocchio', score: 100, image: '' },
      { name: 'Fantasia', score: 95, image: '' },
      { name: 'Dumbo', score: 95, image: '' },
      { name: 'Bambi', score: 91, image: '' },
      { name: 'Saludos Amigos', score: 82, image: '' },
      { name: 'The Three Caballeros', score: 85, image: '' },
      { name: 'Make Mine Music', score: 58, image: '' },
      { name: 'Fun and Fancy Free', score: 73, image: '' },
      { name: 'Melody Time', score: 69, image: '' },
      { name: 'The Adventures of Ichabod and Mr. Toad', score: 89, image: '' },
      { name: 'Cinderella', score: 95, image: '' },
      { name: 'Alice in Wonderland', score: 82, image: '' },
      { name: 'Peter Pan', score: 79, image: '' },
      { name: 'Lady and the Tramp', score: 91, image: '' },
      { name: 'Sleeping Beauty', score: 90, image: '' },
      { name: 'One Hundred and One Dalmatians', score: 98, image: '' },
      { name: 'The Sword in the Stone', score: 65, image: '' },
      { name: 'The Jungle Book', score: 86, image: '' },
      { name: 'The Aristocats', score: 64, image: '' },
      { name: 'Robin Hood', score: 56, image: '' },
      { name: 'The Many Adventures of Winnie the Pooh', score: 100, image: '' },
      { name: 'The Rescuers', score: 79, image: '' },
      { name: 'The Fox and the Hound', score: 75, image: '' },
      { name: 'The Black Cauldron', score: 57, image: '' },
      { name: 'The Great Mouse Detective', score: 79, image: '' },
      { name: 'Oliver & Company', score: 52, image: '' },
      { name: 'The Little Mermaid', score: 92, image: '' },
      { name: 'The Rescuers Down Under', score: 85, image: '' },
      { name: 'Beauty and the Beast', score: 95, image: '' },
      { name: 'Aladdin', score: 96, image: '' },
      { name: 'The Lion King', score: 92, image: '' },
      { name: 'Pocahontas', score: 59, image: '' },
      { name: 'The Hunchback of Notre Dame', score: 80, image: '' },
      { name: 'Hercules', score: 83, image: '' },
      { name: 'Mulan', score: 91, image: '' },
      { name: 'Tarzan', score: 90, image: '' },
      { name: 'Fantasia 2000', score: 80, image: '' },
      { name: 'Dinosaur', score: 65, image: '' },
      { name: 'The Emperor’s New Groove', score: 86, image: '' },
      { name: 'Atlantis: The Lost Empire', score: 48, image: '' },
      { name: 'Lilo & Stitch', score: 86, image: '' },
      { name: 'Treasure Planet', score: 68, image: '' },
      { name: 'Brother Bear', score: 38, image: '' },
      { name: 'Home on the Range', score: 51, image: '' },
      { name: 'Chicken Little', score: 36, image: '' },
      { name: 'Meet the Robinsons', score: 68, image: '' },
      { name: 'Bolt', score: 90, image: '' },
      { name: 'The Princess and the Frog', score: 86, image: '' },
      { name: 'Tangled', score: 89, image: '' },
      { name: 'Winnie the Pooh', score: 90, image: '' },
      { name: 'Wreck-It Ralph', score: 87, image: '' },
      {
        name: 'Frozen',
        score: 89,
        image:
          'https://disney.images.edge.bamgrid.com/ripcut-delivery/v2/variant/disney/bc5f1b5e-737c-457d-ad7f-3e6562aad446/compose?format=webp&label=standard_art_vertical_071&width=800',
      },
      { name: 'Big Hero 6', score: 90, image: '' },
      {
        name: 'Zootopia',
        score: 98,
        image:
          'https://disney.images.edge.bamgrid.com/ripcut-delivery/v2/variant/disney/019b2eff-a3ec-75c0-b82f-ec2415a5b04e/compose?format=webp&label=standard_art_vertical_071&width=800',
      },
      { name: 'Moana', score: 95, image: '' },
      { name: 'Ralph Breaks the Internet', score: 88, image: '' },
      {
        name: 'Frozen 2',
        score: 77,
        image:
          'https://disney.images.edge.bamgrid.com/ripcut-delivery/v2/variant/disney/2d93752a-cbd1-4251-95dc-eb5f65049514/compose?format=webp&label=standard_art_vertical_071&width=800',
      },
      { name: 'Raya and the Last Dragon', score: 93, image: '' },
      { name: 'Encanto', score: 92, image: '' },
      { name: 'Strange World', score: 72, image: '' },
      { name: 'Wish', score: 48, image: '' },
      {
        name: 'Moana 2',
        score: 61,
        image:
          'https://disney.images.edge.bamgrid.com/ripcut-delivery/v2/variant/disney/7f06993f-bb7a-442a-be28-ea326642f07b/compose?format=webp&label=standard_art_vertical_071&width=800',
      },
      {
        name: 'Zootopia 2',
        score: 92,
        image:
          'https://disney.images.edge.bamgrid.com/ripcut-delivery/v2/variant/disney/019d1d25-3ddd-73f2-8f35-ebb74dbf86b1/compose?format=webp&label=standard_art_vertical_071&width=800',
      },
    ],
  },
  {
    title: 'Chips',
    description: 'Brands and flavors of chips',
    players: [
      { name: 'Doritos Nacho Cheese' },
      { name: 'Doritos Cool Ranch' },
      { name: 'Doritos Spicy Nacho' },
      { name: 'Doritos Spicy Sweet Chili' },
      { name: 'Doritos Golden Sriracha' },
      { name: 'Doritos Tapatío' },
      { name: 'Pringles' },
      { name: 'Sour Cream & Onion Pringles' },
      { name: 'Salt & Vinegar Pringles' },
      { name: 'Pizza Pringles' },
      { name: 'BBQ Pringles' },
      { name: 'Honey Mustard Pringles' },
      { name: 'Extra Hot Chili Lime Pringles' },
      { name: 'Fritos' },
      { name: 'Chili Cheese Fritos' },
      { name: 'Fritos Scoops' },
      { name: 'Takis Original' },
      { name: 'Takis Fuego' },
      { name: 'Classic Lay’s' },
      { name: 'Barbecue Lay’s' },
      { name: 'Sour Cream & Onion Lay’s' },
      { name: 'Salt & Vinegar Lay’s' },
      { name: 'Baked Lay’s' },
      { name: 'Wavy Lay’s' },
      { name: 'Lay’s Stax' },
      { name: 'Tostitos' },
      { name: 'Tostitos Scoops' },
      { name: 'Tostitos Hint of Lime' },
      { name: 'Mission Tortilla Strips' },
      { name: 'Late July Tortilla Chips' },
      { name: 'Cheetos Crunchy' },
      { name: 'Cheetos Crunchy Flamin’ Hot' },
      { name: 'Cheetos Puffs' },
      { name: 'Cheetos Puffs Flamin’ Hot' },
      { name: 'Chester’s Fries' },
      { name: 'Ruffles Original' },
      { name: 'Ruffles Cheddar & Sour Cream' },
      { name: 'Ruffles Sour Cream & Onion' },
      { name: 'Ruffles All Dressed' },
      { name: 'Sun Chips' },
      { name: 'French Onion Sun Chips' },
      { name: 'Harvest Cheddar Sun Chips' },
      { name: 'Garden Salsa Sun Chips' },
      { name: 'Funyuns' },
      { name: 'Bugles' },
      { name: 'Veggie straws' },
      { name: 'Kettle Potato Chips Sea Salt' },
      { name: 'Kettle Potato Chips Jalapeño' },
      { name: 'Kettle Krinkle Cut Potato Chips Salt & Fresh Ground Pepper' },
      { name: 'Hawaiian Sweet Maui Onion Kettle Style Potato Chips' },
      { name: 'PopCorners Sea Salt' },
      { name: 'PopCorners White Cheddar' },
      { name: 'Stacy’s Simply Naked Pita Chips' },
      { name: 'Miss Vickie’s Sea Salt' },
      { name: 'Miss Vickie’s Jalapeño' },
      { name: 'Miss Vickie’s Dill Pickle' },
      { name: 'popchips Sea Salt' },
      { name: 'popchips Barbeque' },
      { name: 'Cheez-It Snap’d' },
      { name: 'Terra Classic' },
      { name: 'Torres Black Truffle' },
      { name: 'Chili & Lime Flavored Rolled Tortilla Chips' },
      { name: 'Turtle Chips Sweet Corn Flavor' },
      { name: 'Turtle Chips Honey Butter Flavor' },
    ],
  },
];

export default tournaments;
